### PR TITLE
Add test target for iojs v1, v2, v3, nodejs v4

### PR DESCRIPTION
**Pull request by sanemat**
- Add test target for iojs v1, v2, v3
- Add test target nodejs v4
- Use Install-Product node instead of Update-NodeJsInstallation (appveyor)
  - http://help.appveyor.com/discussions/suggestions/810-nodejs-400-is-out
    `Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)`
    command doesn't work with Node 4 yet.
  - https://github.com/nodejs/nan/issues/444#issuecomment-138896865

### CODE REVIEW

**Comment by sanemat** [comment]
@satazor ping :camel:

**Comment by sanemat** [comment]
@satazor ping :walking:

**Comment by satazor** [comment]
Sorry I'm currently in vacations. Will review this once I get back.

**Comment by sanemat** [comment]
I understand. Thanks!

**Comment by jcrugzz** [comment]
LGTM :+1:

**Pull request merged**
